# Generated by Django 4.0.5 on 2022-06-24 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_remove_course_subject_course_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='my_courses', to=settings.AUTH_USER_MODEL, verbose_name='students'),
        ),
    ]
