# Generated by Django 4.0.5 on 2022-06-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('p', 'published'), ('d', 'draft')], default='d', max_length=10, verbose_name='status'),
        ),
    ]
