# Generated by Django 4.0.5 on 2022-06-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
    ]
